// Files store - file management, tabs, terminal
export {
  $files,
  $openTabs,
  $activeTabId,
  $dirtyFileIds,
  $isTerminalOpen,
  $terminalOutput,
  $isCreatingFile,
  $newFileName,
  $selectedTemplate,
  $selectedCode,
  $isAgentRunning,
  $activeFile,
  setFiles,
  addFile,
  updateFile,
  removeFile,
  setOpenTabs,
  addOpenTab,
  removeOpenTab,
  setActiveTabId,
  markDirty,
  markClean,
  setIsTerminalOpen,
  addTerminalOutput,
  clearTerminalOutput,
  setIsCreatingFile,
  setNewFileName,
  setSelectedTemplate,
  setSelectedCode,
  setIsAgentRunning,
  handleFileChange,
  openFile,
  closeTab,
  resetFilesStore,
} from './filesStore';

// Chat store - messages, input, generation
export {
  $chatMessages,
  $chatInput,
  $isGenerating,
  $chatScrollFn,
  $messageCount,
  $lastMessage,
  setChatMessages,
  addChatMessage,
  updateChatMessage,
  removeChatMessage,
  clearChatMessages,
  setChatInput,
  setIsGenerating,
  setChatScrollFn,
  scrollChatToBottom,
  createMessage,
  resetChatStore,
} from './chatStore';

// Editor store - editor content, preview
export {
  $editorContent,
  $editorLanguage,
  $cursorPosition,
  $editorSelection,
  $isPreviewOpen,
  $previewUrl,
  $previewPort,
  $backgroundUrl,
  $tabContextMenu,
  $hasSelection,
  setEditorContent,
  setEditorLanguage,
  setCursorPosition,
  setEditorSelection,
  clearEditorSelection,
  setIsPreviewOpen,
  setPreviewUrl,
  setPreviewPort,
  setBackgroundUrl,
  setTabContextMenu,
  openPreview,
  closePreview,
  resetEditorStore,
} from './editorStore';

// Theme store - theme management
export {
  $currentThemeId,
  $currentTheme,
  $isDarkMode,
  $availableThemes,
  setCurrentThemeId,
  setTheme,
  setThemeById,
  toggleDarkMode,
  initializeTheme,
  resetThemeStore,
} from './themeStore';

// Agent store - agent mode, AI config
export {
  $agentMode,
  $planMode,
  $agentStatus,
  $activeRunId,
  $completedRunIds,
  $alibabaApiKey,
  $alibabaModel,
  $isAgentActive,
  $agentModeLabel,
  setAgentMode,
  setPlanMode,
  toggleAgentMode,
  togglePlanMode,
  setAgentStatus,
  setActiveRunId,
  markRunCompleted,
  isActiveRun,
  setAlibabaApiKey,
  setAlibabaModel,
  generateRunId,
  resetAgentStore,
} from './agentStore';

// UI store - panels, modals
export {
  $leftPanelOpen,
  $rightPanelOpen,
  $leftPanelTab,
  $leftPanelWidth,
  $rightPanelWidth,
  $isSettingsOpen,
  $isShortcutsOpen,
  $isThemeSelectorOpen,
  $isGlobalSearchOpen,
  $isCommandPaletteOpen,
  ACTIVITY_ITEMS,
  $isAnyModalOpen,
  setLeftPanelOpen,
  toggleLeftPanel,
  setRightPanelOpen,
  toggleRightPanel,
  setLeftPanelTab,
  handleActivityClick,
  setLeftPanelWidth,
  setRightPanelWidth,
  setIsSettingsOpen,
  openSettings,
  closeSettings,
  setIsShortcutsOpen,
  openShortcuts,
  closeShortcuts,
  setIsThemeSelectorOpen,
  openThemeSelector,
  closeThemeSelector,
  setIsGlobalSearchOpen,
  openGlobalSearch,
  closeGlobalSearch,
  setIsCommandPaletteOpen,
  toggleCommandPalette,
  openCommandPalette,
  closeCommandPalette,
  closeAllModals,
  resetUiStore,
} from './uiStore';

export type { LeftTab } from './uiStore';

// React hooks for stores
export * from './hooks';

// Store provider for initialization
export { StoreProvider, useStoreSync } from './StoreProvider';